version: "3"
services:
  app:
    image: brandnewbox/bnb-ruby:2.6-postgresql
    command: bundle exec rails server -b 0.0.0.0
    env_file: .docker-development-vars
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
volumes:
  bundle_cache:
  node_modules:
